# 第4章 取得資料來源
## 匯入外部資料

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### 匯入.xlsx

In [2]:
import pandas as pd
import numpy as np

In [ ]:
# 基本匯入
import pandas as pd
df = pd.read_excel(r"..\data\test.xlsx")
df

In [ ]:
#路徑前面不加r
df = pd.read_excel("../data/test.xlsx")
df

In [ ]:
#指定匯入哪個Sheet
df = pd.read_excel(r"..\data\test.xlsx", sheet_name="工作表1")
df

In [3]:
file_path = r"/content/drive/MyDrive/Colab Notebooks/03 用excel學python(書本範例)/12-3.xlsx"
# sheet_name=None  : All worksheets.
dict1 = pd.read_excel(file_path, sheet_name=None,usecols = [1,2,3,4])

In [5]:
dict1['7月']

   使用者ID 客戶分類  區域  7月銷量
0  59224   A類  北區     6
1  55295   B類  南區    37
2  46035   A類  中區     8
3   2459   C類  北區     7
4  22179   B類  南區     9
5  22557   A類  中區    42

In [ ]:
df = pd.read_excel(r"..\data\test.xlsx", sheet_name = 0)
df

In [ ]:
df = pd.read_excel(r"..\data\test.xlsx", sheet_name = 0, index_col = 0)
df

In [ ]:
#使用 0 號列作為欄索引
df = pd.read_excel(r"..\data\test.xlsx", sheet_name = 0,header = 0)
df

In [ ]:
#使用 1 號列作為欄索引
df = pd.read_excel(r"..\data\test.xlsx", sheet_name = 0,header = 1)
df

In [ ]:
#  代表原表格沒有欄位說明
df = pd.read_excel(r"..\data\test.xlsx", sheet_name = 0,header = None)
df

In [ ]:
#匯入指定欄
df = pd.read_excel(r"..\data\test.xlsx", usecols = [0,3,2])
df

In [ ]:
# 以列表形式匯入多個指定欄
df = pd.read_excel(r"..\data\test.xlsx", usecols = [0,2])
df

In [14]:
file_path = r"/content/drive/MyDrive/Colab Notebooks/03 用excel學python(書本範例)/data/新竹市重要遊憩據點遊客人次統計.xlsx"
#df = pd.read_excel(file_path,index_col=0,usecols = [0,1,3,4],skiprows=12,skipfooter=18 )
df = pd.read_excel(file_path,index_col=0,usecols = [0,1,3,4] )
df

             十八尖山       城隍廟      新竹漁港
期別
108年1月   138881.0  186932.0  226935.0
108年2月   137512.0  251404.0  219437.0
108年3月   101301.0  157317.0  241011.0
108年4月   186020.0  205830.0  272600.0
108年5月   160695.0  212146.0  309255.0
108年6月   169084.0  187465.0  331952.0
108年7月   144669.0  198434.0  244742.0
108年8月   135557.0  231224.0  355109.0
108年9月   127176.0  195564.0  383046.0
108年10月  180991.0  191720.0  361919.0
108年11月  180144.0  216609.0  388662.0
108年12月  147301.0  278915.0  324479.0
109年1月   192081.0  241389.0  452276.0
109年2月   170677.0  214330.0  346007.0
109年3月   190673.0  191038.0  348776.0
109年4月   176280.0  182500.0  436020.0
109年5月   176766.0  180354.0  479606.0
109年6月   157671.0  132915.0  418083.0
109年7月   152906.0  156496.0  405958.0
109年8月   134013.0  245491.0  443330.0
109年9月   123727.0  220832.0  379548.0
109年10月  155288.0  297404.0  471760.0
109年11月  160638.0  242025.0  366255.0
109年12月  174896.0  215972.0  283667.0
110年1月   224536.0  277326.0  446103.0
110年2月   147966.0  278132.0  425314.0
110年3月   217611.0  243618.0  523491.0
110年4月   158943.0  244093.0  423958.0
110年5月   129345.0   38142.0  314924.0
110年6月    93927.0   25047.0  298521.0
110年7月   133773.0   48399.0  428844.0
110年8月    26141.0  106127.0  282740.0
110年9月    28926.0  109313.0  274224.0
110年10月   32948.0  144550.0  269061.0
110年11月   30831.0  135528.0  207825.0
110年12月   28384.0  116170.0  136424.0
111年1月    26263.0  156624.0  157671.0
111年2月    21763.0  158399.0  165439.0
111年3月    32646.0  147422.0  177777.0
111年4月    25660.0  136987.0  188819.0
111年5月    22674.0  111606.0  167380.0
111年6月    24283.0  121314.0  190631.0

In [13]:
df = pd.read_excel(file_path, index_col =0,usecols =[0,1,3,4],
                     skiprows = lambda x: 0 < x < 13 or x > 24 )
#df.rename(columns={'十八尖山':'A','城隍廟':'B','新竹漁港':'C'},inplace=True) 
df.index.name=""
df

             十八尖山       城隍廟      新竹漁港

109年1月   192081.0  241389.0  452276.0
109年2月   170677.0  214330.0  346007.0
109年3月   190673.0  191038.0  348776.0
109年4月   176280.0  182500.0  436020.0
109年5月   176766.0  180354.0  479606.0
109年6月   157671.0  132915.0  418083.0
109年7月   152906.0  156496.0  405958.0
109年8月   134013.0  245491.0  443330.0
109年9月   123727.0  220832.0  379548.0
109年10月  155288.0  297404.0  471760.0
109年11月  160638.0  242025.0  366255.0
109年12月  174896.0  215972.0  283667.0

### 匯入.csv

In [ ]:
import pandas as pd
df = pd.read_csv(r"C:\DataSet\新竹市重要遊憩據點.csv",encoding='big5',index_col =0,usecols =[0,1,3,4],
                     skiprows = lambda x: 0 < x < 13 or x > 24)
df.info()

In [ ]:
import pandas as pd
df = pd.read_csv(r"C:\DataSet\STOCK_DAY_2330_202209.csv",
                 thousands=',',index_col =0,encoding='big5',skiprows=1,skipfooter=5,engine='python')
df = df.drop(columns=['成交金額','成交筆數','漲跌價差','Unnamed: 9'])
df = df.rename(columns={'成交股數':'Volume','開盤價':'Open','最高價':'High','最低價':'Low','收盤價':'Close'})
cols = df.columns.to_list()
cols = cols[1:] + cols[:1]
df = df[cols]
df.index.name = 'Date'
df

In [ ]:
idx = df.index.map(lambda x : '-'.join([str(int(x[:3])+1911),x[4:6],x[7:]]))
df.index = pd.to_datetime(idx)  #  你要傳入一個已經長得很像日期的字串一維陣列
df.index.name = 'Date'

'''
idx 的內容
Index(['2022-09-01', '2022-09-02', '2022-09-05', '2022-09-06', '2022-09-07',
       '2022-09-08', '2022-09-12', '2022-09-13', '2022-09-14', '2022-09-15',
       '2022-09-16', '2022-09-19', '2022-09-20', '2022-09-21', '2022-09-22',
       '2022-09-23', '2022-09-26', '2022-09-27', '2022-09-28', '2022-09-29',
       '2022-09-30'],
      dtype='object', name='Date')
'''

In [ ]:
# idx = df.index.to_list()
# idx = list(map( lambda x : '-'.join([str(int(x[:3])+1911),x[4:6],x[7:]]) ,idx ))
# df.index = pd.to_datetime(idx)  
# df.index.name = 'Date'
# df.index

In [ ]:
#idx = df.index.to_list()
#idx
# df.index = pd.to_datetime([ '-'.join([str(int(item.split('/')[0])+1911),item.split('/')[1],item.split('/')[2]]) for item in idx ])
#df.index = pd.to_datetime([ '-'.join([str(int(item[:3])+1911),item[4:6],item[7:]]) for item in idx ])

In [ ]:
import mplfinance as mpf
mpf.plot(df)

In [ ]:
mpf.plot(df,type='candle')

In [ ]:
mpf.plot(df,type='line')

In [ ]:
mpf.plot(df,type='candle',mav=(3,6,9))

In [ ]:
mpf.plot(df,type='candle',mav=(3,6,9),volume=True)

In [ ]:
rng = pd.date_range(pd.Timestamp("2022-01-01"),
                    periods=365, freq='d')
rng

In [ ]:
rng1 = rng.strftime('%Y-%m-%d')
rng1

#### pandas.Series.map  and  pandas.Series.apply

In [ ]:
import numpy as np
s = pd.Series(['cat', 'dog', np.nan, 'rabbit'])
s

In [ ]:
s.map({'cat': 'kitten', 'dog': 'puppy'})  #  利用字典來對映修正指定的一維陣列元素

In [ ]:
s.map('I am a {}'.format)  #  利用函式來對映所有的一維陣列元素

In [ ]:
s.map('I am a {}'.format, na_action='ignore')  #  忽略空值，利用函式來對映所有的一維陣列元素

In [ ]:
s = pd.Series([20, 21, 12],
              index=['London', 'New York', 'Helsinki'])
s

In [ ]:
def square(x):
    return x ** 2
s.apply(square)

In [ ]:
s.apply(lambda x: x ** 2)

In [ ]:
def subtract_custom_value(x, custom_value):
    return x - custom_value

In [ ]:
s.apply(subtract_custom_value, args=(5,)) # 可以順便傳入一些引數給指定的函式

In [ ]:
def add_custom_values(x, **kwargs):
    for month in kwargs:
        x += kwargs[month]
    return x

In [ ]:
s.apply(add_custom_values, june=30, july=20, august=25)

In [ ]:
s.apply(np.log)

#### pandas.DataFrame.apply  and  pandas.DataFrame.applymap

In [ ]:
df = pd.DataFrame([[4, 9]] * 3, columns=['A', 'B'])
df

In [ ]:
df.apply(np.sqrt)  #  沒有其他參數被使用的情況下，效果同 applymap，所有元素都會跑一遍
#df.applymap(np.sqrt)

In [ ]:
df.apply(np.sum, axis=0)

In [ ]:
df.apply(np.sum, axis=1)

In [ ]:
df.apply(lambda x: [1, 2], axis=1) # 產生三列 [1,2]

In [ ]:
df.apply(lambda x: [1, 2], axis=1, result_type='expand') #  產生三列 [1,2] ，並將元素打開成二行

In [ ]:
df.apply(lambda x: pd.Series([1, 2], index=['foo', 'bar']), axis=1)
#  產生三列 [1,2] ，並將元素打開成二行，並提供欄名

In [ ]:
df.apply(lambda x: [1, 2], axis=1, result_type='broadcast')
#  產生三列 [1,2] ，並將元素打開成二行，而且自動給文字欄名

In [ ]:
# 範例
import pandas as pd
import numpy as np
df = pd.read_excel(r"成績單.xlsx")
df['平均'] = df.iloc[:,2:-3].apply(np.average, axis=1)
df['名次'] = df['平均'].rank(method='min',ascending=False)
df = df.astype({'名次': 'uint8'})
#df.info()

df['備註']=(df['平均']>60)
df = df.replace({'備註':{True:'及格', False:'不及格'}})

# df['備註']=(df['平均']>60).map({True:'及格',False:'不及格'})

# df.loc[  df['平均']>=60 ,'備註' ] = '及格'
# df.loc[  df['平均']<60  ,'備註' ] = '不及格'

In [ ]:
df.head(5)

In [ ]:
#  多重分類方法一
lst1 = []
for item in df['平均'] :
    if item >= 90 :
        lst1.append('A')
    elif item >= 80 :
        lst1.append('B')
    elif item >= 70 :
        lst1.append('C')
    elif item >= 60 :
        lst1.append('D')
    else :
        lst1.append('E')
df1 = df.copy()
df1['等級']=lst1
df1

In [ ]:
#  多重分類方法二
def new_column(row):
    if row['平均'] >= 90 :
        return 'A'
    elif row['平均'] >= 80 :
        return 'B'
    elif row['平均'] >= 70 :
        return 'C'
    elif row['平均'] >= 60 :
        return 'D'
    else :
        return 'E'
df1 = df.copy()
df1['等級'] = df.apply(new_column, axis=1)
df1

In [ ]:
#  多重分類方法三
df1 = df.copy()
df1["等級"] = np.nan
df1["等級"] = df1["等級"].where(~ ( (df1['平均'] <= 100) & (df1['平均'] >= 90) ), 'A') \
                        .where(~ ( (df1['平均'] <   90) & (df1['平均'] >= 80) ), 'B') \
                        .where(~ ( (df1['平均'] <   80) & (df1['平均'] >= 70) ), 'C') \
                        .where(~ ( (df1['平均'] <   70) & (df1['平均'] >= 60) ), 'D') \
                        .where(~ ( (df1['平均'] <   60)                       ), 'E')
df1.head(5)
# https://towardsdatascience.com/the-most-efficient-if-elif-else-in-pandas-d4a7d4502d50
# ~ ( (df1['平均']<=100) & (df1['平均']>=80) )

In [ ]:
#  多重分類方法三
df1 = df.copy()
df1["等級"] = np.nan
df1["等級"] = df1["等級"].mask( ( (df1['平均'] <= 100) & (df1['平均'] >= 90) ), 'A') \
                        .mask( ( (df1['平均'] <   90) & (df1['平均'] >= 80) ), 'B') \
                        .mask( ( (df1['平均'] <   80) & (df1['平均'] >= 70) ), 'C') \
                        .mask( ( (df1['平均'] <   70) & (df1['平均'] >= 60) ), 'D') \
                        .mask( ( (df1['平均'] <   60)                       ), 'E')
df1.head(5)

In [ ]:
#  多重分類方法四
df1 = df.copy()
df1["等級"] = np.nan
con =[ (df1['平均'] <= 100) & (df1['平均'] >= 90),
       (df1['平均'] <   90) & (df1['平均'] >= 80),
       (df1['平均'] <   80) & (df1['平均'] >= 70),
       (df1['平均'] <   70) & (df1['平均'] >= 60),
       (df1['平均'] <   60)
     ]
test=[ 'A' , 'B' ,'C' ,'D' ,'E'  ]
df1["等級"] = np.select(con,test)
df1.head(5)

In [ ]:
y = np.arange(5)
con =[ y<4 ,  y>0  ]
test=[ y   ,  y**2 ]
np.select(con,test)

In [ ]:
con

In [ ]:
test

In [ ]:
df['姓    名'].isin(['陳依利','陳威利','陳嘉祥','陳大鈞','陳凱成','陳傑龍'])  #  這要用在欄位內容有多個重複值的地方，如業務員

In [ ]:
df['姓    名'].str.slice(0,1)

In [ ]:
'陳' in '威陳利'

## pd.Series.where，pd.DataFrame.where 的用法

In [ ]:
s = pd.Series(range(5))

In [ ]:
s.where(s > 0)   # pd.Series.where

In [ ]:
s.mask(s > 0)    # pd.Series.mask

In [ ]:
s.where(s > 1, 10)  # pd.Series.where

In [ ]:
df = pd.DataFrame(np.arange(10).reshape(-1, 2), columns=['A', 'B'])

In [ ]:
df

In [ ]:
m = ( df % 3 == 0 )

In [ ]:
m

In [ ]:
df.where(m, -df)  # pd.DataFrame.where

In [ ]:
df.where(m, -df) == np.where(m, df, -df)

In [ ]:
df.where(m, -df) == df.mask(~m, -df)

### 匯入.csv

In [ ]:
df = pd.read_csv(r"..\data\test1.csv")
df

In [ ]:
df = pd.read_csv(r"..\data\test1.csv",sep = " ")
df

In [ ]:
# 指定讀取列數
df = pd.read_csv(r"..\data\test1.csv",sep = " ",nrows = 2)
df

In [ ]:
df1 = pd.read_csv(r"..\data\test2.csv",encoding = "utf-8")
df1

In [ ]:
df1 = pd.read_csv(r"..\data\test2.csv")
df1

In [ ]:
df1 = pd.read_csv(r"..\data\test3.csv",encoding = "big5")
df1

In [ ]:
df1 = pd.read_csv(r"..\data\test.csv")
df1

In [ ]:
df1 = pd.read_csv(r"..\data\test.csv", engine = "python",encoding = "utf-8-sig")
df1

### 匯入.txt

In [ ]:
#利用read_table()匯入.txt
import pandas as pd
df1 = pd.read_csv(r"..\data\test.txt",sep = " ")
df1

## 新增資料
（本節無範例）

## 熟悉資料
### 利用head預覽前幾行

In [ ]:
df = pd.read_csv(r"..\data\test_head.csv")
df

In [ ]:
df.head() #預設顯示前5列

In [ ]:
df.head(2)#只顯示前2列

### 利用shape取得資料表的大小

In [ ]:
df = pd.read_csv(r"..\data\test.csv")
df

In [ ]:
df.shape

### 利用info取得資料類型

In [ ]:
df

In [ ]:
df = pd.read_excel(r"..\data\test.xlsx")
df
df.info()

### 利用describe取得數值分佈情況

In [ ]:
df.describe()

In [ ]:
# 含有多欄數值型別欄位的DataFrame
df = pd.DataFrame([[20,5000,2],[25,8000,3],[30,9000,3],[28,7000,2]], columns = ["年齡","收入","家屬數"])
df

In [ ]:
df.describe()

## Part Of A Whole

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# create 10 circles with different radii
r = np.random.randint(5,15, size=10)

class C():
    def __init__(self,r):
        self.N = len(r)
        self.x = np.ones((self.N,3))
        self.x[:,2] = r
        maxstep = 2*self.x[:,2].max()
        length = np.ceil(np.sqrt(self.N))
        grid = np.arange(0,length*maxstep,maxstep)
        gx,gy = np.meshgrid(grid,grid)
        self.x[:,0] = gx.flatten()[:self.N]
        self.x[:,1] = gy.flatten()[:self.N]
        self.x[:,:2] = self.x[:,:2] - np.mean(self.x[:,:2], axis=0)

        self.step = self.x[:,2].min()
        self.p = lambda x,y: np.sum((x**2+y**2)**2)
        self.E = self.energy()
        self.iter = 1.

    def minimize(self):
        while self.iter < 1000*self.N:
            for i in range(self.N):
                rand = np.random.randn(2)*self.step/self.iter
                self.x[i,:2] += rand
                e = self.energy()
                if (e < self.E and self.isvalid(i)):
                    self.E = e
                    self.iter = 1.
                else:
                    self.x[i,:2] -= rand
                    self.iter += 1.

    def energy(self):
        return self.p(self.x[:,0], self.x[:,1])

    def distance(self,x1,x2):
        return np.sqrt((x1[0]-x2[0])**2+(x1[1]-x2[1])**2)-x1[2]-x2[2]

    def isvalid(self, i):
        for j in range(self.N):
            if i!=j: 
                if self.distance(self.x[i,:], self.x[j,:]) < 0:
                    return False
        return True

    def plot(self, ax):
        for i in range(self.N):
            circ = plt.Circle(self.x[i,:2],self.x[i,2] )
            ax.add_patch(circ)

c = C(r)

fig, ax = plt.subplots(subplot_kw=dict(aspect="equal"))
ax.axis("off")

c.minimize()

c.plot(ax)
ax.relim()
ax.autoscale_view()
plt.show()

In [ ]:
# libraries
import matplotlib.pyplot as plt
import squarify    # pip install squarify (algorithm for treemap)
import pandas as pd

# Create a data frame with fake data
df = pd.DataFrame({'nb_people':[8,3,4,2], 'group':["group A", "group B", "group C", "group D"] })

# plot it
squarify.plot(sizes=df['nb_people'], label=df['group'], alpha=.8 )
plt.axis('off')
plt.show()

In [ ]:
#libraries
import matplotlib.pyplot as plt
import squarify # pip install squarify (algorithm for treemap)
 
# Change color
squarify.plot(sizes=[13,22,35,5], label=["group A", "group B", "group C", "group D"], color=["red","green","blue", "grey"], alpha=.4 )
plt.axis('off')
plt.show()

In [ ]:
#libraries
import matplotlib
import matplotlib.pyplot as plt
import squarify # pip install squarify (algorithm for treemap)
 
# Create a dataset:
my_values=[i**3 for i in range(1,100)]
 
# create a color palette, mapped to these values
cmap = matplotlib.cm.Blues
mini=min(my_values)
maxi=max(my_values)
norm = matplotlib.colors.Normalize(vmin=mini, vmax=maxi)
colors = [cmap(norm(value)) for value in my_values]
 
# Change color
squarify.plot(sizes=my_values, alpha=.8, color=colors )
plt.axis('off')
plt.show()

In [ ]:
from pprint import pprint as pp
import circlify as circ
circles = circ.circlify([19, 17, 13, 11, 7, 5, 3, 2, 1], show_enclosure=True)
pp(circles)

In [ ]:
from pprint import pprint as pp
import circlify as circ
data = [
        0.05, {'id': 'a2', 'datum': 0.05},
        {'id': 'a0', 'datum': 0.8, 'children': [0.3, 0.2, 0.2, 0.1], },
        {'id': 'a1', 'datum': 0.1, 'children': [
            {'id': 'a1_1', 'datum': 0.05}, {'datum': 0.04}, 0.01],
        },
    ]
circles = circ.circlify(data, show_enclosure=True)
pp(circles)

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'Name': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Value': [10, 2, 23, 87, 12, 65]
})

In [ ]:
# import the circlify library
import circlify

# compute circle positions:
circles = circlify.circlify(
    df['Value'].tolist(), 
    show_enclosure=False, 
    target_enclosure=circlify.Circle(x=0, y=0, r=1)
)

In [ ]:
# import libraries
import circlify
import matplotlib.pyplot as plt

# Create just a figure and only one subplot
fig, ax = plt.subplots(figsize=(10,10))

# Title
ax.set_title('Basic circular packing')

# Remove axes
ax.axis('off')

# Find axis boundaries
lim = max(
    max(
        abs(circle.x) + circle.r,
        abs(circle.y) + circle.r,
    )
    for circle in circles
)
plt.xlim(-lim, lim)
plt.ylim(-lim, lim)

# list of labels
labels = df['Name']

# print circles
for circle, label in zip(circles, labels):
    x, y, r = circle
    ax.add_patch(plt.Circle((x, y), r, alpha=0.2, linewidth=2))
    plt.annotate(
          label, 
          (x,y ) ,
          va='center',
          ha='center'
     )